### ISSUE TITLE
Collect all results

### ISSUE THREAD

**Issue by sladesamuel** [sladesamuel/amazon-jobs-monitor#13]
Use a map, driven by the number of pages, to grab all results from every page and collate them all together in a single collection.

# Tasks
- [x] Add Map step to Step Function
- [x] Call Fetch Page Content lambda in Map
- [x] Create new Lambda to collate results
- [x] Add new Lambda after Map step in Step Function to collate all results into a single list
