### ISSUE TITLE
Find and track unseen results

### ISSUE THREAD

**Issue by sladesamuel** [sladesamuel/amazon-jobs-monitor#6]
Implement the DynamoDB steps to lookup and track unseen results. All newly tracked results should be returned and combined into a list.

# Tasks
- [x] Create the DynamoDB Table to track Jobs
- [x] Create a Map step in the Step Function to iterate over all jobs
- For each job:
  - [x] Get item from DynamoDB by Job Id
  - [x] If it doesn't exist, insert it, and return the Job in the output
  - [x] If it already exists, return an empty output
